import 'dart:io';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../core/enums.dart';
import '../models/attendance_model.dart';
import '../services/supabase_storage_service.dart';

class AttendanceRepository {
  final SupabaseClient _supabase = Supabase.instance.client;
  final SupabaseStorageService _storageService = SupabaseStorageService();
  
  final String _tableName = 'attendances';

  /// Get today's attendance for a user.
  Future<AttendanceModel?> getTodayAttendance(String userId) async {
    final now = DateTime.now();
    final todayStr = DateTime(now.year, now.month, now.day).toIso8601String();

    try {
      final data = await _supabase
          .from(_tableName)
          .select()
          .eq('userId', userId)
          .eq('date', todayStr)
          .limit(1)
          .maybeSingle()
          .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Koneksi lambat saat mengambil data absen.'));

      if (data == null) return null;
      return AttendanceModel.fromMap(data);
    } catch (_) {
      return null;
    }
  }

  /// Check in — create new attendance record.
  Future<AttendanceModel> checkIn({
    required String userId,
    required String employeeName,
    required String shiftId,
    required String shiftName,
    double? latitude,
    double? longitude,
    double? distanceFromOffice,
    LocationStatus locationStatus = LocationStatus.unknown,
    AttendanceStatus attendanceStatus = AttendanceStatus.present,
    String? photoPath,
  }) async {
    final existing = await getTodayAttendance(userId);
    if (existing != null) {
      throw Exception('Anda sudah melakukan absen masuk hari ini.');
    }

    final now = DateTime.now();
    String? publicPhotoUrl;

    if (photoPath != null) {
      final file = File(photoPath);
      final storagePath = await _storageService
          .uploadAttendanceSelfie(file, userId, 'checkin')
          .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Upload foto absen terlalu lama. Periksa koneksi internet Anda.'));
      publicPhotoUrl = _storageService.getPublicUrl(storagePath);
    }

    final record = AttendanceModel(
      id: '', // Will be generated by Supabase (uuid) or we can generate it here
      userId: userId,
      employeeName: employeeName,
      shiftId: shiftId,
      shiftName: shiftName,
      date: DateTime(now.year, now.month, now.day),
      checkInTime: now,
      checkInPhotoPath: publicPhotoUrl,
      latitude: latitude,
      longitude: longitude,
      distanceFromOffice: distanceFromOffice,
      locationStatus: locationStatus,
      attendanceStatus: attendanceStatus,
      createdAt: now,
    );

    // Insert and return the newly created row (which includes the auto-generated id)
    final insertedData = await _supabase.from(_tableName)
        .insert(record.toMap()..remove('id')) // Remove empty id to let DB generate UUID
        .select()
        .single()
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Gagal menyimpan absensi karena internet lambat.'));
        
    return AttendanceModel.fromMap(insertedData);
  }

  /// Check out — update existing attendance record.
  Future<AttendanceModel> checkOut({
    required String attendanceId,
    String? photoPath,
  }) async {
    final data = await _supabase.from(_tableName).select().eq('id', attendanceId).maybeSingle()
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Koneksi lambat saat mengambil data absensi.'));

    if (data == null) {
      throw Exception('Record absensi tidak ditemukan');
    }

    final currentRecord = AttendanceModel.fromMap(data);

    if (!currentRecord.hasCheckedIn) {
      throw Exception('Anda belum melakukan absen masuk.');
    }

    if (currentRecord.hasCheckedOut) {
      throw Exception('Anda sudah melakukan absen pulang hari ini.');
    }

    String? publicPhotoUrl;
    if (photoPath != null) {
      final file = File(photoPath);
      final storagePath = await _storageService
          .uploadAttendanceSelfie(file, currentRecord.userId, 'checkout')
          .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Upload foto absen terlalu lama. Periksa koneksi internet Anda.'));
      publicPhotoUrl = _storageService.getPublicUrl(storagePath);
    }

    final updated = currentRecord.copyWith(
      checkOutTime: DateTime.now(),
      checkOutPhotoPath: publicPhotoUrl ?? currentRecord.checkOutPhotoPath,
    );

    await _supabase.from(_tableName).update(updated.toMap()).eq('id', attendanceId)
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Gagal memperbarui absensi karena internet lambat.'));
        
    return updated;
  }

  /// Get attendance history for a user.
  Future<List<AttendanceModel>> getHistory(String userId) async {
    final data = await _supabase
        .from(_tableName)
        .select()
        .eq('userId', userId)
        .order('date', ascending: false)
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Koneksi lambat saat mengambil riwayat.'));

    return data.map((map) => AttendanceModel.fromMap(map)).toList();
  }

  Future<List<AttendanceModel>> getAll() async {
    final data = await _supabase.from(_tableName)
        .select()
        .order('date', ascending: false)
        .order('checkInTime', ascending: false)
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Koneksi lambat saat mengambil semua riwayat.'));
        
    return data.map((map) => AttendanceModel.fromMap(map)).toList();
  }

  /// Get attendance records by date range.
  Future<List<AttendanceModel>> getByDateRange(
    DateTime start,
    DateTime end, {
    String? userId,
  }) async {
    final startStr = start.toIso8601String();
    final endStr = end.toIso8601String();

    var query = _supabase
        .from(_tableName)
        .select()
        .gte('date', startStr)
        .lte('date', endStr);
        
    if (userId != null) {
      query = query.eq('userId', userId);
    }
    
    final data = await query.order('date', ascending: false)
        .timeout(const Duration(seconds: 15), onTimeout: () => throw Exception('Koneksi lambat saat mengambil laporan bulanan.'));
    
    return data.map((map) => AttendanceModel.fromMap(map)).toList();
  }
}
