// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAph90bDJlfdpZx8Buo8ugc-fnmOezMa-Y',
    appId: '1:901454923490:web:818848d68ef34ba4a900bb',
    messagingSenderId: '901454923490',
    projectId: 'absensigeo-145f2',
    authDomain: 'absensigeo-145f2.firebaseapp.com',
    storageBucket: 'absensigeo-145f2.firebasestorage.app',
    measurementId: 'G-2YZFTEZYR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWYxYxv3dqUsXy2fpBUMTY46LcSABsU30',
    appId: '1:901454923490:android:35127917a603c553a900bb',
    messagingSenderId: '901454923490',
    projectId: 'absensigeo-145f2',
    storageBucket: 'absensigeo-145f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1D5nJI7ItKzxpenOLnaDk-I2gb-O4_cg',
    appId: '1:901454923490:ios:9b21894406b67abaa900bb',
    messagingSenderId: '901454923490',
    projectId: 'absensigeo-145f2',
    storageBucket: 'absensigeo-145f2.firebasestorage.app',
    iosBundleId: 'com.example.mahligaiBs',
  );
}
